mytask:7main.o 7task.o 7inout.o
	gcc 7main.o 7task.o 7inout.o -o mytask

7main.o:7main.c 7.h
	gcc -std=c11 -c 7main.c -o 7main.o

7task.o:7task.c 7.h
	gcc -std=c11 -c 7task.c -o 7task.o

7inout.o:7inout.c 7.h
	gcc -std=c11 -c 7inout.c -o 7inout.o


